### ISSUE TITLE
Box not found

### ISSUE THREAD

**Issue by mishanon** [JarJarBernie/jimmybox#1]
Hello

Could you help me?

URL: ["https://atlas.hashicorp.com/sternpunkt/jimmybox"]
Error: The requested URL returned error: 404 Not Found

**Comment by ghost** [comment]
Hi @mishanon!

sorry for my late answer!

when are you getting this issue? Have you been usign oder versions of Jimmybox before or is this your first setup?

kind regards

Bernhard

**Comment by JarJarBernie** [comment]
jimmybox 2.1 is now hosted on amazon s3. should not happen any more.
bernie
