### ISSUE TITLE
Setting up repositories on different PHP versions

### ISSUE THREAD

**Issue by marcuswiseman** [JarJarBernie/jimmybox#4]
This is more of a query than an issue. 

I've upgraded from the old jimmybox to the new one.

I am able to setup repositories on php7.3,  though when i change /provisioning/hosts/ files with the following code, its not recognising the php version.

`
<IfModule mod_fastcgi.c>
                <FilesMatch ".+\.ph(p[345]?|t|tml)$">
                        SetHandler php56-fcgi-www
                </FilesMatch>
</IfModule>
`

I'm not sure if im doing something wrong or what but im not understanding how to switch php versions. The old box had vhosts per php version.

Thanks for any support :)

**Comment by JarJarBernie** [comment]
Hi Marcus,
sorry for my late answer. Can you show the complete content of your provisioning file?

Kind regards
Bernhard

**Comment by JarJarBernie** [comment]
Hi Marcus,
i changed the handler in Jimmybox 3.0.0, switching PHP Version in your custom hosts should be easier now!
