### ISSUE TITLE
vagrant up: File upload source ...ssl must exist

### ISSUE THREAD

**Issue by agustavo87** [JarJarBernie/jimmybox#5]
I just cloned the repository, go to de 'jimmybox' folder and 'vagrant up' and get this error on Windows 10:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
 File upload source file D:/Gustavo/www/jimmybox/provisioning/ssl must exist
```

I'm kind of noob in this, and i look in the README but i can't find mention to this. I think i can get through deletting some things, but i want to know if i missed something or there's some detail than is missing.

**Comment by JarJarBernie** [comment]
Hi gustaveco,

thanks for your request. I fixed this one ;-)

Please just git pull and try again.

Alternatively please create an empty directory in D:/Gustavo/www/jimmybox/provisioning/ssl and try vagrant up again.

Hope this helps.

Kind regards,
Bernhard
